language: node_js
node_js: 
  - "stable" 
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database bankatest;' -U postgres
  - npm run initialDb
script:
 - npm test
after_success:
- npm run coveralls
