language: node_js
node_js: 
  - "stable" 
cache:
  directories:
    - "node_modules"
services:
  - postgresql
before_script:
  - psql -c 'create database bankatest;' -U postgres
  - npm run initialDb
  - psql -c `insert into users values ('Laetitia', 'Kabeho', 'kabehola@banka.com','$2b$10$iRVZqOFQiriZHTuaJuFE9er9zP03Nbl7oykEP94P.1Bzi0ZB/sn3e', 'staff', 'true') ON CONFLICT (email) DO NOTHING;` -U postgres
script:
 - npm test
after_success:
- npm run coveralls
